#!/usr/bin/python
# -*- coding: utf-8 -*-

DATA_BIT_VAL = 0
ACK_BIT_VAL = 1
SYN_BIT_VAL = 2
SYN_ACK_BIT_VAL = 3
NAK_BIT_VAL = 4
BYE_BIT_VAL = 8
MINIMUM_LEN = 11
MAXIMUM_LEN = 1024
SLIDING_WINDOW_SIZE = 10
RECIEVER_TIME_OUT = 4
FRAME_SIZE = 1024
HANDSHAKE_TIME_OUT = 2
SLIDE_TIME = 0.1